
services:
  
  serveur-web-entreprise:
    image: nginx
    privileged: true
    networks:
      Reseau_DMZ:
        ipv4_address: 120.0.33.22
    container_name: serveur_web_entreprise

  serveur-web:
    image: nginx
    privileged: true
    container_name: serveur_web
    networks:
      Reseau_services_FAI:
        ipv4_address: 120.0.38.8
  box:
    image: 3x3cut0r/isc-dhcp-server:latest # image dhcp
    restart: always
    privileged: true
    command: tail -f /dev/null
    networks:
      particuliers:
        ipv4_address: 120.0.34.2
      reseau_Prive:
        ipv4_address: 192.168.1.2
    ports:
      - "67:67/udp"   # Expose le port pour dhcp
    volumes:
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf   
    tty: true   
    stdin_open: true
    container_name: box_particulier

  routeur-particuliers:
      build : image-routeur-particuliers
      restart: always
      privileged: true
      command: tail -f /dev/null
      networks:
        particuliers:
          ipv4_address: 120.0.34.5
        Reseau_Coeur:
          ipv4_address: 120.0.40.5
      container_name: Routeur_acces_particuliers


  routeur-services-fai:
      build: image-routeur-services-fai
      restart: always
      privileged: true
      command: tail -f /dev/null
      networks:
        Reseau_services_FAI:
          ipv4_address: 120.0.38.3
        Reseau_Coeur:
          ipv4_address: 120.0.40.3
      container_name: Routeur_services_FAI  

  
  dns-global:
      build: dns-global
      privileged: true
      networks:
        Reseau_services_FAI:
          ipv4_address: 120.0.38.5
      
      container_name: serveur_dns
  dns-entreprise:
      build: dns-entreprise
      privileged: true
      networks:
        Reseau_DMZ:
          ipv4_address: 120.0.33.21
      
      container_name: serveur_dns_entreprise

  clientparticulier:
      image: debian:latest
      restart: always
      privileged: true
      command: tail -f /dev/null 
      networks:
        reseau_Prive:
          ipv4_address: 192.168.1.3
      container_name: particulier

  routeur-acces-entreprises:
      build : image-routeur-acces-entreprises
      restart: always
      privileged: true
      command: tail -f /dev/null
      networks:
        Reseau_Coeur:
          ipv4_address: 120.0.40.4
        Reseau_acces_entreprises:
          ipv4_address: 120.0.32.4
      container_name: Routeur_acces_entreprises

  routeur-entreprise-site-principal:
      build : image-routeur-Entreprise-site-principal
      restart: always
      privileged: true
      command: tail -f /dev/null 
      networks:
        Reseau_acces_entreprises:
          ipv4_address: 120.0.32.3
        Reseau_DMZ:
          ipv4_address: 120.0.33.18
        Reseau_service_administratif:
          ipv4_address: 120.0.42.2
      container_name: Routeur_entreprise_site_principal
  
  routeur-interco : 
      build : image-routeur-interco
      restart: always
      privileged: true
      command: tail -f /dev/null 
      networks:
        Reseau_Coeur:
          ipv4_address: 120.0.40.2
      container_name: Routeur_interco

networks:
  particuliers:
   
    ipam:
      driver: default
      config:
        - subnet: "120.0.34.0/23"
  
  reseau_Prive:
    
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
  
  Reseau_Coeur:
    
    ipam:
      driver: default
      config:
        - subnet: "120.0.40.0/27"

  Reseau_acces_entreprises:
    
    ipam:
      driver: default
      config:
        - subnet: "120.0.32.0/24"
 
  Reseau_DMZ:
    
    ipam:
      driver: default
      config:
        - subnet: "120.0.33.0/27"
  
   
  Reseau_services_FAI:
    
    ipam:
      driver: default
      config:
        - subnet: "120.0.38.0/27"

  Reseau_service_administratif:
    
    ipam:
      driver: default
      config:
        - subnet: "120.0.42.0/27"