
services:
  
  box:
    image: 3x3cut0r/isc-dhcp-server:latest # image dhcp
    restart: always
    privileged: true
    command: tail -f /dev/null
    networks:
      particuliers:
        ipv4_address: 120.0.34.2
      reseau_Prive:
        ipv4_address: 192.168.1.2
    ports:
      - "67:67/udp"   # Expose le port pour dhcp
    volumes:
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf   
    tty: true   
    stdin_open: true


  routeur-particuliers:
      build : image-routeur-particuliers
      restart: always
      privileged: true
      command: tail -f /dev/null
      networks:
        particuliers:
          ipv4_address: 120.0.34.5
        Reseau_Coeur:
          ipv4_address: 120.0.40.5


  routeur-dmz:
      build: image-dmz
      restart: always
      privileged: true
      command: tail -f /dev/null
      networks:
        Reseau_DMZ:
          ipv4_address: 120.0.38.3
        Reseau_Coeur:
          ipv4_address: 120.0.40.3
      volumes:
        - ./image-dmz:/etc/frr:z

  
  DNS-DMZ:
      image: ubuntu/bind9:latest
      restart: always
      privileged: true
      command: tail -f /dev/null
      networks:
        Reseau_DMZ:
          ipv4_address: 120.0.38.5

  clientparticulier:
      image: alpine       
      restart: always
      privileged: true
      command: tail -f /dev/null 
      networks:
        reseau_Prive:
          ipv4_address: 192.168.1.3

  routeur-entreprise:
      build : image-routeur-Entreprise
      restart: always
      privileged: true
      command: tail -f /dev/null
      networks:
        Reseau_Coeur:
          ipv4_address: 120.0.40.4
        Reseau_Entreprise:
          ipv4_address: 120.0.32.2

  routeur-entreprise-dns:
      build : image-routeur-Entreprise-DNS
      restart: always
      privileged: true
      command: tail -f /dev/null 
      networks:
        Reseau_Entreprise:
          ipv4_address: 120.0.32.3
        Reseau_Entreprise_DNS:
          ipv4_address: 120.0.33.18

networks:
  particuliers:
    driver: macvlan
    ipam:
      config:
        - subnet: "120.0.34.0/23"
  reseau_Prive:
    
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
  
  Reseau_Coeur:
    driver: macvlan
    ipam:
      config:
        - subnet: "120.0.40.0/27"

  Reseau_Entreprise:
    driver: macvlan
    ipam:
      config:
        - subnet: "120.0.32.0/24"
 
  Reseau_Entreprise_DNS:
    driver: macvlan
    ipam:
      config:
        - subnet: "120.0.33.0/27"
  
   
  Reseau_DMZ:
    driver: macvlan
    ipam:
      config:
        - subnet: "120.0.38.0/27"